// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlAwuneRLcdmHylnoe7XunF2dsItIxvtg',
    appId: '1:1090298493103:web:3d6492b2c2202f6e92fc5a',
    messagingSenderId: '1090298493103',
    projectId: 'f2-guide-up',
    authDomain: 'f2-guide-up.firebaseapp.com',
    storageBucket: 'f2-guide-up.appspot.com',
    measurementId: 'G-K2VE0P5LER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb4E4P8sLXQm_4ZAFo0NJiFuaBInbnmME',
    appId: '1:1090298493103:android:2ab5d2efd7800c6b92fc5a',
    messagingSenderId: '1090298493103',
    projectId: 'f2-guide-up',
    storageBucket: 'f2-guide-up.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyConRXxFGO9NAZrdtcmG7Ljru-KN1oUsmM',
    appId: '1:1090298493103:ios:0a6528dab75bf3d392fc5a',
    messagingSenderId: '1090298493103',
    projectId: 'f2-guide-up',
    storageBucket: 'f2-guide-up.appspot.com',
    iosClientId: '1090298493103-u3ofug8dntsrqhledi9pm65uk4bvhgoj.apps.googleusercontent.com',
    iosBundleId: 'com.guideup.guideUp',
  );
}
